# Generated by Django 5.1.4 on 2024-12-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_category_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
